# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-18 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAttempted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('score', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Question Attempted',
                'verbose_name_plural': 'Questions Attempted',
            },
        ),
    ]
