# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-19 16:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_auto_20161118_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionattempted',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quizzes.Quiz'),
        ),
    ]
