# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20151216_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
