# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quiz.Team'),
            preserve_default=False,
        ),
    ]
