# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_formation_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='positions',
            field=models.ManyToManyField(to='quiz.Position'),
        ),
    ]
