# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 22:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_play_positions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='formation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Formation'),
        ),
    ]
