# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_auto_20160104_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='blockingAssignmentPlayerIndex',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='blockingAssignmentUnitIndex',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='play',
            name='players',
            field=models.ManyToManyField(blank=True, null=True, to='quiz.Player'),
        ),
    ]
