# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_formation_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='offensiveFormationID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
