# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-12 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_position_playerindex'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='CBAssignmentPlayerID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='CBAssignmentPlayerIndex',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='CBAssignmentPlayerPosition',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
