# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-12 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_auto_20160112_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='formations',
            field=models.ManyToManyField(blank=True, null=True, to='quiz.Formation'),
        ),
    ]
