# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-15 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0018_auto_20160115_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='is_being_tested',
            field=models.BooleanField(default=False),
        ),
    ]
