# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-16 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0019_auto_20160115_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='test',
            name='in_progress',
            field=models.BooleanField(default=False),
        ),
    ]
