# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-19 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0021_test_coach_who_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
