# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-28 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0023_testresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='testresult',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
