# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-28 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0025_auto_20160128_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Player'),
        ),
    ]
