# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-28 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0026_testresult_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='time_taken',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
