# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-28 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0027_testresult_time_taken'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testresult',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='testresult',
            name='correct_plays',
            field=models.ManyToManyField(blank=True, null=True, to='quiz.Play'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='missed_plays',
            field=models.ManyToManyField(blank=True, null=True, related_name='missed_plays', to='quiz.Play'),
        ),
    ]
