# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-28 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0028_auto_20160128_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='skipped_plays',
            field=models.ManyToManyField(blank=True, null=True, related_name='skipped_playes', to='quiz.Play'),
        ),
    ]
