# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-01 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0029_testresult_skipped_plays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='incorrect_guesses',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='skips',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
