# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-02 15:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0030_auto_20160201_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResultPlay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(blank=True, null=True)),
                ('correct', models.BooleanField(default=False)),
                ('incorrect', models.BooleanField(default=False)),
                ('skipped', models.BooleanField(default=False)),
                ('play', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Play')),
            ],
        ),
        migrations.AlterField(
            model_name='testresult',
            name='skipped_plays',
            field=models.ManyToManyField(blank=True, null=True, related_name='skipped_plays', to='quiz.Play'),
        ),
        migrations.AddField(
            model_name='testresultplay',
            name='testresult',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.TestResult'),
        ),
    ]
