# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-02 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0031_auto_20160202_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresultplay',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='testresultplay',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
