# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-12 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0033_testresult_string_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='runCoordinates',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
