# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-09 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0034_auto_20160209_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='CBAssignmentPlayerPosition',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
