# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-13 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0035_position_cbassignmentplayerposition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='gapYardX',
            field=models.IntegerField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='gapYardY',
            field=models.IntegerField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='zoneHeight',
            field=models.IntegerField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='zoneWidth',
            field=models.IntegerField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='zoneYardY',
            field=models.IntegerField(blank=True, max_length=200, null=True),
        ),
    ]
