# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-13 14:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0034_position_runcoordinates'),
        ('quiz', '0037_auto_20160213_0300'),
    ]

    operations = [
    ]
