# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-23 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0038_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='players',
            field=models.ManyToManyField(blank=True, to='quiz.Player'),
        ),
        migrations.AlterField(
            model_name='test',
            name='formations',
            field=models.ManyToManyField(blank=True, to='quiz.Formation'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='correct_plays',
            field=models.ManyToManyField(blank=True, to='quiz.Play'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='missed_plays',
            field=models.ManyToManyField(blank=True, related_name='missed_plays', to='quiz.Play'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='skipped_plays',
            field=models.ManyToManyField(blank=True, related_name='skipped_plays', to='quiz.Play'),
        ),
    ]
