# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-03 16:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0042_position_blockingassignmentobject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='blockingAssignmentObject',
        ),
    ]
