# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-07 21:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0045_position_runassignmentobject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='runAssignmentObject',
            new_name='runAssignment',
        ),
    ]
