# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-15 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0046_auto_20160607_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='defenseID',
            field=models.CharField(default='0', max_length=10),
            preserve_default=False,
        ),
    ]
