# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-24 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0047_play_defenseid'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
