# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-24 18:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0048_test_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='due_date',
        ),
    ]
