# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-24 18:41
from __future__ import unicode_literals

from django.db import migrations, models
import quiz.models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0049_remove_test_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='deadline',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
