# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-11 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0050_auto_20160624_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='year',
            field=models.CharField(blank=True, choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('RS FR', 'Redshirt Freshman'), ('RS SO', 'Redshirt Sophomore'), ('RS JR', 'Redshirt Junior'), ('RS SR', 'Redshirt Senior')], max_length=25, null=True),
        ),
    ]
