# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-18 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0051_player_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='player',
        ),
        migrations.AddField(
            model_name='test',
            name='players',
            field=models.ManyToManyField(to='quiz.Player'),
        ),
    ]
