# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-25 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0053_test_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='blockingCoordinates',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
