# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-29 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0054_position_blockingcoordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='formationJson',
            field=models.TextField(blank=True, null=True),
        ),
    ]
