# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-30 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0055_formation_formationjson'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='playJson',
            field=models.TextField(blank=True, null=True),
        ),
    ]
