# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-01 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0056_play_playjson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formation',
            name='offensiveFormationID',
        ),
        migrations.RemoveField(
            model_name='formation',
            name='offensivePlayers',
        ),
        migrations.RemoveField(
            model_name='formation',
            name='playName',
        ),
        migrations.AddField(
            model_name='formation',
            name='scout',
            field=models.NullBooleanField(default=True),
        ),
    ]
