# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-01 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0057_auto_20160901_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='play',
            name='defenseID',
        ),
        migrations.AddField(
            model_name='play',
            name='scout',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='formation',
            name='scout',
            field=models.BooleanField(default=False),
        ),
    ]
