# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-07 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0059_auto_20160901_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='scoutName',
            field=models.CharField(default='', max_length=100),
        ),
    ]
