# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-20 19:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0063_auto_20160912_2329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='play',
            options={'ordering': ['-created_at']},
        ),
    ]
