# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-28 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0065_auto_20160926_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='scoutName',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
