# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-24 19:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_auto_20161024_1902'),
        ('quiz', '0066_auto_20160928_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formation',
            name='team',
        ),
        migrations.RemoveField(
            model_name='play',
            name='formation',
        ),
        migrations.RemoveField(
            model_name='play',
            name='team',
        ),
        migrations.RemoveField(
            model_name='position',
            name='formation',
        ),
        migrations.RemoveField(
            model_name='test',
            name='coach_who_created',
        ),
        migrations.RemoveField(
            model_name='test',
            name='formations',
        ),
        migrations.RemoveField(
            model_name='test',
            name='players',
        ),
        migrations.RemoveField(
            model_name='test',
            name='team',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='correct_plays',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='missed_plays',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='player',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='skipped_plays',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='test',
        ),
        migrations.RemoveField(
            model_name='testresultplay',
            name='play',
        ),
        migrations.RemoveField(
            model_name='testresultplay',
            name='testresult',
        ),
        migrations.DeleteModel(
            name='Formation',
        ),
        migrations.DeleteModel(
            name='Play',
        ),
        migrations.DeleteModel(
            name='Position',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.DeleteModel(
            name='TestResult',
        ),
        migrations.DeleteModel(
            name='TestResultPlay',
        ),
    ]
