# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-18 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.BooleanField(default=False)),
                ('unit', models.CharField(blank=True, choices=[['O', 'Offense'], ['D', 'Defense'], ['S', 'Special Teams']], max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(blank=True, max_length=30, null=True)),
                ('year', models.CharField(blank=True, choices=[['FR', 'Freshman'], ['SO', 'Sophomore'], ['JR', 'Junior'], ['SR', 'Senior'], ['RFR', 'Redshirt Freshman'], ['RSO', 'Redshirt Sophomore'], ['RJR', 'Redshirt Junior'], ['RSR', 'Redshirt Senior']], max_length=3, null=True)),
                ('number', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('position_group', models.BooleanField(default=False)),
                ('position_type', models.CharField(choices=[['QB', 'Quarterback'], ['SK', 'Skill Position'], ['OL', 'Offensive Lineman'], ['DL', 'Defensive Lineman'], ['LB', 'Linebacker'], ['DB', 'Defensive Back'], ['SP', 'Specialist']], default='Skill Position', max_length=20)),
                ('abbreviation', models.CharField(blank=True, max_length=3, null=True)),
                ('players', models.ManyToManyField(blank=True, to='dashboard.Player')),
            ],
            options={
                'verbose_name': 'Player Group',
                'verbose_name_plural': 'Player Groups',
            },
        ),
    ]
