# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-17 23:22
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='myUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_a_player', models.BooleanField(default=False)),
                ('avatar_image', models.ImageField(blank=True, null=True, upload_to='profile')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('position', models.CharField(blank=True, max_length=10, null=True)),
                ('year', models.CharField(blank=True, choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('RS FR', 'Redshirt Freshman'), ('RS SO', 'Redshirt Sophomore'), ('RS JR', 'Redshirt Junior'), ('RS SR', 'Redshirt Senior')], max_length=25, null=True)),
                ('unit', models.CharField(blank=True, max_length=20, null=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('is_being_tested', models.BooleanField(default=False)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('starter', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('position_group', models.BooleanField(default=False)),
                ('position_type', models.CharField(choices=[['QB', 'Quarterback'], ['SK', 'Skill Position'], ['OL', 'Offensive Lineman'], ['DL', 'Defensive Lineman'], ['LB', 'Linebacker'], ['DB', 'Defensive Back'], ['SP', 'Specialist']], default='Skill Position', max_length=20)),
                ('abbreviation', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'verbose_name': 'Player Group',
                'verbose_name_plural': 'Player Groups',
            },
        ),
        migrations.CreateModel(
            name='QuestionAttempted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('score', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Question Attempted',
                'verbose_name_plural': 'Questions Attempted',
            },
        ),
        migrations.CreateModel(
            name='UserMethods',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
