# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-17 23:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
        ('playbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionattempted',
            name='concept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='playbook.Concept'),
        ),
        migrations.AddField(
            model_name='questionattempted',
            name='formation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='playbook.Formation'),
        ),
        migrations.AddField(
            model_name='questionattempted',
            name='play',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='playbook.Play'),
        ),
        migrations.AddField(
            model_name='questionattempted',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Player'),
        ),
    ]
