# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-16 19:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20160115_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='team',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='user',
        ),
        migrations.DeleteModel(
            name='Athlete',
        ),
    ]
