# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-22 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0022_test_name'),
        ('dashboard', '0005_myuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('players', models.ManyToManyField(to='quiz.Player')),
            ],
        ),
    ]
