# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-22 18:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0022_test_name'),
        ('dashboard', '0006_playergroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='playergroup',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Team'),
        ),
    ]
