# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-03 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_playergroup_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='avatar_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile'),
        ),
    ]
