# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-08 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_myuser_avatar_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='title',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
