# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-11 16:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20160708_0348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playergroup',
            options={'verbose_name': 'Player Group', 'verbose_name_plural': 'Player Groups'},
        ),
    ]
