# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-14 05:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20160711_1617'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playergroup',
            options={'ordering': ['pk'], 'verbose_name': 'Player Group', 'verbose_name_plural': 'Player Groups'},
        ),
    ]
