# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-09 01:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0053_test_team'),
        ('dashboard', '0011_auto_20160714_0539'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(default='offense', max_length=100)),
                ('defensivePlayers', models.ManyToManyField(related_name='defensive_player', to='quiz.Player')),
                ('offensivePlayers', models.ManyToManyField(related_name='offensive_player', to='quiz.Player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Team')),
            ],
        ),
    ]
