# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-16 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_concept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='concept',
            name='unit',
            field=models.CharField(default='offense', max_length=25),
        ),
    ]
