# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-28 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20160816_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='defensivePlayers',
            field=models.ManyToManyField(blank=True, related_name='defensive_player', to='quiz.Player'),
        ),
        migrations.AlterField(
            model_name='concept',
            name='offensivePlayers',
            field=models.ManyToManyField(blank=True, related_name='offensive_player', to='quiz.Player'),
        ),
    ]
