# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-01 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20160828_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concept',
            name='defensivePlayers',
        ),
        migrations.RemoveField(
            model_name='concept',
            name='offensivePlayers',
        ),
        migrations.AddField(
            model_name='concept',
            name='scout',
            field=models.BooleanField(default=False),
        ),
    ]
