# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-10 04:30
from __future__ import unicode_literals

import dashboard.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0060_play_scoutname'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0016_auto_20160901_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('unit', models.CharField(default='offense', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('players', models.ManyToManyField(to='quiz.Player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Team')),
            ],
        ),
    ]
