# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-13 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0063_auto_20160912_2329'),
        ('dashboard', '0017_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='concepts',
            field=models.ManyToManyField(to='dashboard.Concept'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='formations',
            field=models.ManyToManyField(to='quiz.Formation'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='plays',
            field=models.ManyToManyField(to='quiz.Play'),
        ),
    ]
