# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-10 04:33
from __future__ import unicode_literals

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='deadline',
            field=models.DateTimeField(default=dashboard.models.deadline_time),
        ),
    ]
