# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-13 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_auto_20160913_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='concepts',
            field=models.ManyToManyField(blank=True, to='dashboard.Concept'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='formations',
            field=models.ManyToManyField(blank=True, to='quiz.Formation'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='plays',
            field=models.ManyToManyField(blank=True, to='quiz.Play'),
        ),
    ]
