# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-10 04:37
from __future__ import unicode_literals

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_auto_20160910_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='deadline',
            field=models.DateTimeField(blank=True, default=dashboard.models.deadline_time, null=True),
        ),
    ]
