# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-13 05:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0063_auto_20160912_2329'),
        ('dashboard', '0019_auto_20160913_0232'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAttempted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('result', models.IntegerField()),
                ('concept', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Concept')),
                ('formation', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Formation')),
                ('play', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Play')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Player')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Quiz')),
                ('team', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Team')),
            ],
        ),
    ]
