# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-14 17:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_questionattempted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionattempted',
            options={'verbose_name': 'Question Attempted', 'verbose_name_plural': 'Questions Attempted'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name': 'Quiz', 'verbose_name_plural': 'Quizzes'},
        ),
        migrations.RenameField(
            model_name='questionattempted',
            old_name='result',
            new_name='score',
        ),
    ]
