# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-14 20:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_auto_20160914_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionattempted',
            name='concept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Concept'),
        ),
        migrations.AlterField(
            model_name='questionattempted',
            name='formation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Formation'),
        ),
        migrations.AlterField(
            model_name='questionattempted',
            name='play',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Play'),
        ),
    ]
