# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-20 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0063_auto_20160912_2329'),
        ('dashboard', '0024_auto_20160919_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='submissions',
            field=models.ManyToManyField(blank=True, related_name='submissions', to='quiz.Player'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='players',
            field=models.ManyToManyField(related_name='players', to='quiz.Player'),
        ),
    ]
