# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-20 19:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_auto_20160920_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 9, 20, 19, 42, 20, 190157, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='concept',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 9, 20, 19, 42, 27, 363257, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
