# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-20 19:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_auto_20160920_1942'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concept',
            options={'ordering': ['-created_at']},
        ),
    ]
