# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-21 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_auto_20160920_1944'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playergroup',
            options={'verbose_name': 'Player Group', 'verbose_name_plural': 'Player Groups'},
        ),
        migrations.AddField(
            model_name='playergroup',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='playergroup',
            name='display_in_creation_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playergroup',
            name='position_group',
            field=models.BooleanField(default=False),
        ),
    ]
