# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-21 16:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_auto_20160921_0431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playergroup',
            name='display_in_creation_mode',
        ),
    ]
