# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-22 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_playergroup_position_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playergroup',
            name='players',
            field=models.ManyToManyField(blank=True, to='quiz.Player'),
        ),
    ]
