# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-24 19:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0066_auto_20160928_1749'),
        ('dashboard', '0031_auto_20160922_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(default='offense', max_length=100)),
                ('scout', models.BooleanField(default=False)),
                ('formationJson', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Team')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('scoutName', models.CharField(blank=True, default='', max_length=100)),
                ('scout', models.BooleanField(default=False)),
                ('playJson', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Formation')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Team')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startX', models.FloatField()),
                ('startY', models.FloatField()),
                ('name', models.CharField(max_length=100)),
                ('routeCoordinates', models.CharField(blank=True, max_length=200, null=True)),
                ('runCoordinates', models.CharField(blank=True, max_length=200, null=True)),
                ('blockingCoordinates', models.CharField(blank=True, max_length=200, null=True)),
                ('motionCoordinates', models.CharField(blank=True, max_length=200, null=True)),
                ('progressionRank', models.IntegerField(blank=True, null=True)),
                ('playerIndex', models.IntegerField(blank=True, null=True)),
                ('routeNum', models.IntegerField(blank=True, null=True)),
                ('blocker', models.NullBooleanField()),
                ('runner', models.NullBooleanField()),
                ('CBAssignmentPlayerID', models.IntegerField(blank=True, null=True)),
                ('CBAssignmentPlayerIndex', models.IntegerField(blank=True, null=True)),
                ('CBAssignmentPlayerPosition', models.CharField(blank=True, max_length=200, null=True)),
                ('zoneYardX', models.FloatField(blank=True, null=True)),
                ('zoneYardY', models.FloatField(blank=True, max_length=200, null=True)),
                ('zoneHeight', models.FloatField(blank=True, max_length=200, null=True)),
                ('zoneWidth', models.FloatField(blank=True, max_length=200, null=True)),
                ('gapYardX', models.FloatField(blank=True, max_length=200, null=True)),
                ('gapYardY', models.FloatField(blank=True, max_length=200, null=True)),
                ('blockingAssignmentPlayerIndex', models.IntegerField(blank=True, null=True)),
                ('blockingAssignmentUnitIndex', models.IntegerField(blank=True, null=True)),
                ('blockingAssignmentObject', models.CharField(blank=True, max_length=200, null=True)),
                ('runAssignment', models.CharField(blank=True, max_length=200, null=True)),
                ('formation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Formation')),
            ],
        ),
        migrations.AlterField(
            model_name='questionattempted',
            name='formation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Formation'),
        ),
        migrations.AlterField(
            model_name='questionattempted',
            name='play',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Play'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='formations',
            field=models.ManyToManyField(blank=True, to='dashboard.Formation'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='plays',
            field=models.ManyToManyField(blank=True, to='dashboard.Play'),
        ),
    ]
