# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-17 00:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0067_auto_20161024_1902'),
        ('dashboard', '0032_auto_20161024_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(default='play', max_length=25)),
                ('number_of_questions', models.IntegerField(default=0)),
                ('ordering', models.CharField(default='recent', max_length=25)),
                ('quiz_type', models.CharField(default='identification', max_length=25)),
                ('position', models.CharField(default='', max_length=25)),
                ('type_of_assignment', models.CharField(default='all', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Team')),
            ],
        ),
    ]
