# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-17 18:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0033_customquiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('position', models.CharField(blank=True, max_length=10, null=True)),
                ('year', models.CharField(blank=True, choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('RS FR', 'Redshirt Freshman'), ('RS SO', 'Redshirt Sophomore'), ('RS JR', 'Redshirt Junior'), ('RS SR', 'Redshirt Senior')], max_length=25, null=True)),
                ('unit', models.CharField(blank=True, max_length=20, null=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('is_being_tested', models.BooleanField(default=False)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('starter', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sidebar_image', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('midfield_art', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('endzone_art', models.ImageField(blank=True, null=True, upload_to=b'')),
            ],
        ),
        migrations.AlterField(
            model_name='coach',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Team'),
        ),
        migrations.AlterField(
            model_name='concept',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Team'),
        ),
        migrations.AlterField(
            model_name='customquiz',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Player'),
        ),
        migrations.AlterField(
            model_name='customquiz',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Team'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Team'),
        ),
        migrations.AlterField(
            model_name='play',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Team'),
        ),
        migrations.AlterField(
            model_name='playergroup',
            name='players',
            field=models.ManyToManyField(blank=True, to='dashboard.Player'),
        ),
        migrations.AlterField(
            model_name='playergroup',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Team'),
        ),
        migrations.AlterField(
            model_name='questionattempted',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Player'),
        ),
        migrations.AlterField(
            model_name='questionattempted',
            name='team',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Team'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='players',
            field=models.ManyToManyField(related_name='players', to='dashboard.Player'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='submissions',
            field=models.ManyToManyField(blank=True, related_name='submissions', to='dashboard.Player'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Team'),
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Team'),
        ),
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
