# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 17:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Formation')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_test', models.CharField(max_length=100)),
                ('score', models.IntegerField()),
                ('skips', models.IntegerField()),
                ('incorrect_guesses', models.IntegerField()),
                ('deadline', models.DateTimeField()),
                ('completed', models.BooleanField()),
                ('in_progress', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='starter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Player'),
        ),
        migrations.AddField(
            model_name='play',
            name='players',
            field=models.ManyToManyField(to='quiz.Player'),
        ),
        migrations.AddField(
            model_name='play',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Team'),
        ),
        migrations.AddField(
            model_name='play',
            name='tests',
            field=models.ManyToManyField(to='quiz.Test'),
        ),
    ]
