# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20151216_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='offensivePlayers',
            field=models.ManyToManyField(to='quiz.Player'),
        ),
        migrations.AddField(
            model_name='formation',
            name='playName',
            field=models.CharField(default='formation_example', max_length=100),
            preserve_default=False,
        ),
    ]
