# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20160104_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='routeCoordinates',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
