# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-17 23:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('getsnap', '0001_initial'),
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('playbook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(default='play', max_length=25)),
                ('number_of_questions', models.IntegerField(default=0)),
                ('ordering', models.CharField(default='recent', max_length=25)),
                ('quiz_type', models.CharField(default='identification', max_length=25)),
                ('position', models.CharField(default='', max_length=25)),
                ('type_of_assignment', models.CharField(default='all', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getsnap.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('unit', models.CharField(default='offense', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('concepts', models.ManyToManyField(blank=True, to='playbook.Concept')),
                ('formations', models.ManyToManyField(blank=True, to='playbook.Formation')),
                ('players', models.ManyToManyField(related_name='players', to='dashboard.Player')),
                ('plays', models.ManyToManyField(blank=True, to='playbook.Play')),
                ('submissions', models.ManyToManyField(blank=True, related_name='submissions', to='dashboard.Player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getsnap.Team')),
            ],
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
            },
        ),
    ]
