# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-17 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sidebar_image', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('midfield_art', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('endzone_art', models.ImageField(blank=True, null=True, upload_to=b'')),
            ],
        ),
    ]
