# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-28 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getsnap', '0002_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='payment_status',
            field=models.CharField(default='', max_length=20, null=True),
        ),
    ]
