# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-28 00:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getsnap', '0003_team_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='payment_renew_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 28, 0, 27, 21, 755839)),
        ),
    ]
