# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-28 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getsnap', '0006_auto_20161128_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='payment_renew_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
