# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-28 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getsnap', '0008_team_service_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='field_type',
            field=models.CharField(blank=True, default='HS', max_length=10, null=True),
        ),
    ]
