# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-30 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getsnap', '0009_team_field_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='customer_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
