# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-03 01:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getsnap', '0011_customuser_blocked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='blocked',
        ),
    ]
