# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-21 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getsnap', '0013_activationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='force_password_reset',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='has_set_password',
            field=models.BooleanField(default=True),
        ),
    ]
